/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PRIVATE;

import DTO.PesquisaDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author mello
 */
public class Algoritimo_Pesquisa extends javax.swing.JPanel {

    /**
     * Creates new form Algoritimo_Pesquisa1
     */
    public Algoritimo_Pesquisa(PesquisaDTO objpesquisadto) {
        initComponents();
        setPesquisa(objpesquisadto);
    }

    private void setPesquisa(PesquisaDTO objpesquisadto) {
        addEventMouse(this);
        addEventMouse(algori_pesq);
        addEventMouse(algori_remove);
        algori_pesq.setText(objpesquisadto.getTexto());
        if (objpesquisadto.isHistorico()) {
            algori_pesq.setForeground(new Color(29, 106, 205));
            algori_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/time.png")));
            algori_remove.setCursor(new Cursor(Cursor.HAND_CURSOR));
        } else {
            algori_remove.setText("");

        }

    }

    private void addEventMouse(Component com) {
        com.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                setBackground(new Color(215, 216, 216));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setBackground(Color.WHITE);
            }

        });
    }

    private ActionListener eventClick;
    private ActionListener eventRemove;

    public void addEvent(ActionListener eventClick, ActionListener eventRemove) {
        this.eventClick = eventClick;
        this.eventRemove = eventRemove;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        algori_icon = new javax.swing.JLabel();
        algori_pesq = new javax.swing.JLabel();
        algori_remove = new javax.swing.JLabel();

        algori_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        algori_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/search_small.png"))); // NOI18N

        algori_pesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                algori_pesqMouseClicked(evt);
            }
        });

        algori_remove.setText("Remover");
        algori_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                algori_removeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(algori_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(algori_pesq, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(algori_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(algori_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(algori_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(algori_pesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void algori_removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algori_removeMouseClicked
        if (!algori_remove.getText().trim().equals("")) {
            eventRemove.actionPerformed(null);
        }
    }//GEN-LAST:event_algori_removeMouseClicked

    private void algori_pesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algori_pesqMouseClicked
        eventClick.actionPerformed(null);
    }//GEN-LAST:event_algori_pesqMouseClicked
    
    public String getText() {
        return algori_pesq.getText();
    }
        
    public void setSelected(boolean act) {
        if (act) {
            setBackground(new Color(215, 216, 216));
        } else {
            setBackground(Color.WHITE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algori_icon;
    private javax.swing.JLabel algori_pesq;
    private javax.swing.JLabel algori_remove;
    // End of variables declaration//GEN-END:variables
}
