/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import VIEW.ConfigAparencia;
import PRIVATE.Painel_Pesquisa;
import DTO.PesquisaDTO;
import PRIVATE.EventClick;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPopupMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import org.apache.commons.io.IOUtils;
import org.json.JSONObject;
import org.json.JSONTokener;
import org.openstreetmap.gui.jmapviewer.Coordinate;
import org.openstreetmap.gui.jmapviewer.MapMarkerDot;

/**
 *
 * @author mello
 */
public class AppPrincipalVIEW extends javax.swing.JFrame {

    private JPopupMenu menu;
    private Painel_Pesquisa procura;

    public AppPrincipalVIEW() {
        initComponents();
        this.setTitle("Weathervane");
        setIconImage();
        connectToDatabase();
        centreWindow(this);
        getIPGeo();

        menu = new JPopupMenu();
        procura = new Painel_Pesquisa();
        menu.add(procura);
        menu.setFocusable(false);
        procura.addEventClick(new EventClick() {
            @Override
            public void itemClick(PesquisaDTO objpesquisadto) {
                menu.setVisible(false);
                pesquisa.setText(objpesquisadto.getTexto());
                addHistorico(objpesquisadto.getTexto());
                connectAPI(objpesquisadto.getTexto());
            }

            @Override
            public void itemRemove(Component com, PesquisaDTO objpesquisadto) {
                procura.remove(com);
                RemoveHistorico(objpesquisadto.getTexto());
                menu.setPopupSize(menu.getWidth(), (procura.conseguirTamanhoItem() * 32) + 2);
                if (procura.conseguirTamanhoItem() == 0) {
                    menu.setVisible(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pesquisa = new PRIVATE.TextField();
        temperatura = new javax.swing.JLabel();
        nomeCidade = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        iconAgua = new javax.swing.JLabel();
        iconVento = new javax.swing.JLabel();
        humidade = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JLabel3 = new javax.swing.JLabel();
        ventania = new javax.swing.JLabel();
        jMapViewer1 = new org.openstreetmap.gui.jmapviewer.JMapViewer();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        botaoAparencia = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        botaoSobre = new javax.swing.JMenuItem();
        exitBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesquisa.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/search.png"))); // NOI18N
        pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaMouseClicked(evt);
            }
        });
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaKeyReleased(evt);
            }
        });
        jPanel1.add(pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, -1));

        temperatura.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        temperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperatura.setText(".");
        jPanel1.add(temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 119, 60));

        nomeCidade.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nomeCidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomeCidade.setText(".");
        jPanel1.add(nomeCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 68, 260, 50));

        hora.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora.setText(".");
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 131, -1));

        icone.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 119, 78));

        descricao.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        descricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descricao.setText(".");
        jPanel1.add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 286, 380, 39));

        iconAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8-water-64.png"))); // NOI18N
        jPanel1.add(iconAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 343, 56, 85));

        iconVento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8-wind-48.png"))); // NOI18N
        jPanel1.add(iconVento, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 351, -1, 77));

        humidade.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        humidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        humidade.setText(".");
        jPanel1.add(humidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 387, 144, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Vento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 343, 99, -1));

        JLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        JLabel3.setForeground(new java.awt.Color(204, 204, 204));
        JLabel3.setText("Umidade:");
        jPanel1.add(JLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 343, 138, -1));

        ventania.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        ventania.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ventania.setText(".");
        jPanel1.add(ventania, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 387, 140, -1));
        jPanel1.add(jMapViewer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/fundo-gradiente.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 450, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 440, 580));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jMenuBar1ComponentMoved(evt);
            }
        });

        jMenu1.setText("Configurações");

        botaoAparencia.setText("Aparência");
        botaoAparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAparenciaActionPerformed(evt);
            }
        });
        jMenu1.add(botaoAparencia);

        jMenuBar1.add(jMenu1);

        menuAbout.setText("Ajuda");

        botaoSobre.setText("Sobre");
        botaoSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSobreActionPerformed(evt);
            }
        });
        menuAbout.add(botaoSobre);

        jMenuBar1.add(menuAbout);

        exitBtn.setText("Sair");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(exitBtn);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBar1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1ComponentMoved

    private void botaoSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSobreActionPerformed
        TermosdeServico termos = new TermosdeServico();
        termos.setVisible(true);
        termos.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_botaoSobreActionPerformed

    private void botaoAparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAparenciaActionPerformed
        ConfigAparencia appearance = new ConfigAparencia();
        appearance.setVisible(true);
        appearance.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_botaoAparenciaActionPerformed

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        FormularioLoginVIEW login = new FormularioLoginVIEW();
        login.lembrarLogin.setSelected(false);
        login.setVisible(true);
        // One step at a time   

        dispose();

    }//GEN-LAST:event_exitBtnMouseClicked

    private void pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_UP && evt.getKeyCode() != KeyEvent.VK_DOWN && evt.getKeyCode() != KeyEvent.VK_ENTER) {
            String text = pesquisa.getText().trim().toLowerCase();
            procura.setPesquisa(procurar(text));
            if (procura.conseguirTamanhoItem() > 0) {
                menu.show(pesquisa, 0, pesquisa.getHeight());
                menu.setPopupSize(menu.getWidth(), (procura.conseguirTamanhoItem() * 32) + 2);
            } else {
                menu.setVisible(false);
            }
        }
    }//GEN-LAST:event_pesquisaKeyReleased

    private void pesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            procura.keyUp();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            procura.keyDown();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = procura.getSelectedText();
            pesquisa.setText(texto);
            menu.setVisible(false);
            addHistorico(texto);
            connectAPI(texto);
        }
    }//GEN-LAST:event_pesquisaKeyPressed

    private void pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaMouseClicked
        if (procura.conseguirTamanhoItem() > 0) {
            menu.show(pesquisa, 0, pesquisa.getHeight());
            procura.clearSelected();
        }
    }//GEN-LAST:event_pesquisaMouseClicked

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaActionPerformed

    private List<PesquisaDTO> procurar(String procurar) {
        List<PesquisaDTO> list = new ArrayList<>();
        try {
            String sql = "select DISTINCT cidade, coalesce((select id_historico from historico where cidade=item_salvo limit 1),'') as historico from sugestoes where cidade like ? order by historico DESC, cidade limit 7";

            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setString(1, "%" + procurar + "%");

            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                String texto = rs.getString(1);
                boolean historico = !rs.getString(2).equals("");
                list.add(new PesquisaDTO(texto, historico));
            }
            rs.close();
            pstm.close();
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "AppPrincipalVIEW: " + error);
            return null;
        }
        return list;
    }

    private void RemoveHistorico(String texto) {
        try {
            String sql = "delete from historico where item_salvo=? limit 1";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setString(1, texto);
            pstm.execute();
            pstm.close();
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "AppPrincipalVIEW: " + error);
        }
    }

    private Connection conn;

    private void connectToDatabase() {
        try {
            String url = "jdbc:mysql://sql10.freesqldatabase.com:3306/sql10669278?user=sql10669278&password=NSBMGmXJXQ";
            conn = DriverManager.getConnection(url);

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "AppPrincipalVIEW: " + error);
        }
    }

    private void addHistorico(String texto) {
        try {
            boolean add = true;
            String sql = "select id_historico from historico where item_salvo=? limit 1";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setString(1, texto);
            ResultSet rs = pstm.executeQuery();
            if (rs.next()) {
                add = false;
            }
            rs.close();
            pstm.close();
            if (add) {
                String othersql = "insert into historico (item_salvo) values (?)";
                pstm = conn.prepareStatement(othersql);
                pstm.setString(1, texto);
                pstm.execute();
                pstm.close();
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "AppPrincipalVIEW: " + error);
        }
    }

    // Variáveis globais
    int roundTemp = 0;
    int roundWind = 0;

    public void connectAPI(String texto) {
        try {
            String sql = "SELECT latitude, longitude FROM sugestoes WHERE cidade = ?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setString(1, texto);
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                String lat = rs.getString("latitude");
                String lon = rs.getString("longitude");
                String api = "https://api.openweathermap.org/data/2.5/weather?lat=" + lat + "&lon=" + lon + "&appid=39b4b8957534286d3d7a4a23f5bd3ee6&units=metric&lang=pt_br";

                URL url = null;
                String json = null;

                try {
                    url = new URL(api);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    json = IOUtils.toString(url, "UTF-8");
                } catch (IOException ex) {
                    Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
                }

                JSONObject object = new JSONObject(new JSONTokener(json));

                // Conseguir temperatura
                double getTemp = object.getJSONObject("main").getDouble("temp");
                roundTemp = (int) Math.round(getTemp);

                temperatura.setText(roundTemp + "°C");

                // Descrição da temperatura
                String getTempDesc = object.getJSONArray("weather").getJSONObject(0).getString("description");
                String setTempDesc = capitalizeWords(getTempDesc);

                descricao.setText(setTempDesc);

                // Porcentagem da humidade
                int getHumid = object.getJSONObject("main").getInt("humidity");

                humidade.setText(getHumid + "%");

                // Velocidade do vento
                double getWind = object.getJSONObject("wind").getDouble("speed");
                roundWind = (int) Math.round(getWind);

                ventania.setText(roundWind + " m/s");

                // Nome da cidade
                String country = object.getJSONObject("sys").getString("country");
                if (country.equals("JP") || country.equals("CN")) {
                    String nameCity = object.getString("name");
                    nomeCidade.setText(nameCity);

                } else {
                    //Uso da API de localização
                    try {
                        String newLat = lat.replace(",", ".");
                        String newLon = lon.replace(",", ".");
                        double lati = Double.parseDouble(newLat);
                        double longi = Double.parseDouble(newLon);
                        URL urlLoc = null;
                        urlLoc = new URL("https://nominatim.openstreetmap.org/reverse?lat=" + lati + "&lon=" + longi + "&format=json&zoom=10");
                        try {
                            String jsonLoc = null;
                            jsonLoc = IOUtils.toString(urlLoc, "UTF-8");
                            JSONObject objectLoc = new JSONObject(new JSONTokener(jsonLoc));
                            String getCity = objectLoc.getString("name");

                            nomeCidade.setText(getCity);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                // Colocar o ícone correspondente ao clima
                String iconeCorres = object.getJSONArray("weather").getJSONObject(0).getString("icon");
                URL iconeTemp = null;
                try {
                    iconeTemp = new URL("https://openweathermap.org/img/wn/" + iconeCorres + "@2x.png");
                } catch (MalformedURLException ex) {
                    Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
                }
                BufferedImage iconeLegivel = null;
                try {
                    iconeLegivel = ImageIO.read(iconeTemp);
                } catch (IOException ex) {
                    Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
                }
                ImageIcon iconeVisivel = new ImageIcon(iconeLegivel);
                icone.setIcon(iconeVisivel);

                // Colocar a hora atual
                try {
                    URL horaURL = new URL("https://api.opencagedata.com/geocode/v1/json?q=" + lat + "+" + lon + "&key=bd7b858ce7af4c2a96c17fbfb160e2ae");
                    try {
                        String jsonLoc = null;
                        jsonLoc = IOUtils.toString(horaURL, "UTF-8");
                        JSONObject objectLoc = new JSONObject(new JSONTokener(jsonLoc));
                        String fetchData = objectLoc.getJSONArray("results").getJSONObject(0).getJSONObject("annotations").getJSONObject("timezone").getString("name");

                        ZoneId fuso = ZoneId.of(fetchData);
                        LocalDateTime horaAtual = LocalDateTime.now(fuso);
                        DateTimeFormatter formatado = DateTimeFormatter.ofPattern("HH:mm");
                        String horario = horaAtual.format(formatado);

                        hora.setText(horario);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } catch (MalformedURLException ex) {
                    Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Colocar o lugar correspondente no mapa
                String newLat = lat.replace(",", ".");
                String newLon = lon.replace(",", ".");
                double lati = Double.parseDouble(newLat);
                double longi = Double.parseDouble(newLon);
                Coordinate coordinate = new Coordinate(lati, longi);
                MapMarkerDot marker = new MapMarkerDot(coordinate);
                jMapViewer1.setDisplayPosition(coordinate, 8);
                jMapViewer1.addMapMarker(marker);

            }
            rs.close();
            pstm.close();

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "AppPrincipalVIEW: " + error);
        }

    }

    public void getIPGeo() {
        try {
            URL urlIP = new URL("http://httpbin.org/ip");
            String jsonIP = null;
            try {
                jsonIP = IOUtils.toString(urlIP, "UTF-8");
            } catch (IOException ex) {
                Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
            JSONObject object = new JSONObject(new JSONTokener(jsonIP));
            String getIP = object.getString("origin");

            try {
                URL geoIP = new URL("http://ip-api.com/json/" + getIP + "?fields=status,message,country,region,regionName,city,zip,lat,lon,timezone");
                String jsonGeo = null;
                try {
                    jsonGeo = IOUtils.toString(geoIP, "UTF-8");
                } catch (IOException ex) {
                    Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
                }
                JSONObject objectIP = new JSONObject(new JSONTokener(jsonGeo));
                double lat = objectIP.getDouble("lat");
                double lon = objectIP.getDouble("lon");
                String city = objectIP.getString("city");
                nomeCidade.setText(city);

                // Uso da API de clima
                try {
                    URL urlAPI = new URL("https://api.openweathermap.org/data/2.5/weather?lat=" + lat + "&lon=" + lon + "&appid=39b4b8957534286d3d7a4a23f5bd3ee6&units=metric&lang=pt_br");
                    try {
                        String jsonAPI = null;
                        jsonAPI = IOUtils.toString(urlAPI, "UTF-8");
                        JSONObject objectAPI = new JSONObject(new JSONTokener(jsonAPI));

                        // Conseguir temperatura
                        double getTemp = objectAPI.getJSONObject("main").getDouble("temp");
                        roundTemp = (int) Math.round(getTemp);

                        temperatura.setText(roundTemp + "°C");

                        // Descrição do Clima Atual
                        String getTempDesc = objectAPI.getJSONArray("weather").getJSONObject(0).getString("description");
                        String setTempDesc = capitalizeWords(getTempDesc);

                        descricao.setText(setTempDesc);

                        // Porcentagem da humidade
                        int getHumid = objectAPI.getJSONObject("main").getInt("humidity");

                        humidade.setText(getHumid + "%");

                        // Velocidade do vento
                        double getWind = objectAPI.getJSONObject("wind").getDouble("speed");
                        roundWind = (int) Math.round(getWind);

                        ventania.setText(roundWind + " m/s");

                        // Colocar a hora atual
                        LocalDateTime horaAtual = LocalDateTime.now();
                        DateTimeFormatter formatado = DateTimeFormatter.ofPattern("HH:mm");
                        String horario = horaAtual.format(formatado);
                        hora.setText(horario);

                        // Colocar o ícone correspondente ao clima
                        String iconeCorres = objectAPI.getJSONArray("weather").getJSONObject(0).getString("icon");
                        URL iconeTemp = new URL("https://openweathermap.org/img/wn/" + iconeCorres + "@2x.png");
                        BufferedImage iconeLegivel = ImageIO.read(iconeTemp);
                        ImageIcon iconeVisivel = new ImageIcon(iconeLegivel);
                        icone.setIcon(iconeVisivel);

                        // Colocar o lugar correspondente no mapa
                        Coordinate coordinate = new Coordinate(lat, lon);
                        MapMarkerDot marker = new MapMarkerDot(coordinate);
                        jMapViewer1.setDisplayPosition(coordinate, 8);
                        jMapViewer1.addMapMarker(marker);

                    } catch (IOException ex) {
                        Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (MalformedURLException ex) {
                    Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (MalformedURLException ex) {
                Logger.getLogger(AppPrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void mudarTemp(String unidadeMedida) {
        switch (unidadeMedida) {
            case "°C":
                temperatura.setText(roundTemp + "°C");
                break;
            case "°F":
                int newTempF = (int) (roundTemp * 1.8 + 32);
                temperatura.setText(newTempF + "°F");
                break;
            case "°K":
                int newTempK = (int) (roundTemp + 273.15);
                temperatura.setText(newTempK + "°K");
                break;
        }
        setVisible(false);
        setVisible(true);
    }

    public void mudarVento(String unidadeVento) {
        switch (unidadeVento) {
            case "m/s":
                ventania.setText(roundWind + " m/s");
                break;
            case "Km/h":
                int newRoundWind = (int) (roundWind * 3.6);
                ventania.setText(newRoundWind + " Km/h");
                break;
        }
        setVisible(false);
        setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppPrincipalVIEW().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Assets/perereca_engracada.png")));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel3;
    private javax.swing.JMenuItem botaoAparencia;
    private javax.swing.JMenuItem botaoSobre;
    private javax.swing.JLabel descricao;
    private javax.swing.JMenu exitBtn;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel humidade;
    private javax.swing.JLabel iconAgua;
    private javax.swing.JLabel iconVento;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private org.openstreetmap.gui.jmapviewer.JMapViewer jMapViewer1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JLabel nomeCidade;
    private PRIVATE.TextField pesquisa;
    private javax.swing.JLabel temperatura;
    public javax.swing.JLabel ventania;
    // End of variables declaration//GEN-END:variables

    private void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }

    public static String capitalizeWords(String input) {
        // Split the input string into words
        String[] words = input.split(" ");

        // Capitalize the first letter of each word
        for (int i = 0; i < words.length; i++) {
            if (words[i].length() > 0) {  // Check if the word is not empty
                words[i] = words[i].substring(0, 1).toUpperCase() + words[i].substring(1).toLowerCase();
            }
        }

        // Join the words back into a string
        String result = String.join(" ", words);

        return result;
    }
}
