/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ItemEvent;
import java.util.prefs.Preferences;

/**
 *
 * @author Elenita
 */
public class ConfigAparencia extends javax.swing.JFrame {

    /**
     * Creates new form ConfigAparencia
     */
    public ConfigAparencia() {
        initComponents();
        this.setTitle("Weathervane");
        setIconImage();
        restorePreferences();
        updateUI();
        Color color = new Color(214, 217, 223);
        painelPrincipal.setBackground(color);
        jLabel1.setForeground(Color.black);
        jLabel2.setForeground(Color.black);
        jLabel3.setForeground(Color.black);
        jLabel4.setForeground(Color.black);
        centreWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selecaoCores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelPrincipal.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cor");
        painelPrincipal.add(jLabel1);
        jLabel1.setBounds(28, 37, 96, 17);

        selecaoCores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padrão", "Branco", "Preto" }));
        selecaoCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoCoresActionPerformed(evt);
            }
        });
        painelPrincipal.add(selecaoCores);
        selecaoCores.setBounds(28, 65, 80, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Unidade de V.");
        painelPrincipal.add(jLabel2);
        jLabel2.setBounds(143, 37, 100, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "Km/h" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        painelPrincipal.add(jComboBox1);
        jComboBox1.setBounds(143, 65, 72, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Idioma");
        painelPrincipal.add(jLabel3);
        jLabel3.setBounds(251, 37, 80, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português-Brazil", "Inglês", "Japonês", "Francês" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        painelPrincipal.add(jComboBox2);
        jComboBox2.setBounds(251, 65, 121, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Unidade de C");
        painelPrincipal.add(jLabel4);
        jLabel4.setBounds(143, 105, 110, 17);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F", "°K" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        painelPrincipal.add(jComboBox3);
        jComboBox3.setBounds(143, 133, 72, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/fundo-gradiente.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        painelPrincipal.add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 360);

        getContentPane().add(painelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 356));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String selectedColor = null;
    String selectedWindUnit = null;
    String selectedLanguage = null;
    String selectedTemperatureUnit = null;

    private void restorePreferences() {
        Preferences prefs = Preferences.userNodeForPackage(ConfigAparencia.class);
        selectedColor = prefs.get("selectedColor", "Default");
        selectedWindUnit = prefs.get("selectedWindUnit", "m/s");
        selectedLanguage = prefs.get("selectedLanguage", "Português-Brazil");
        selectedTemperatureUnit = prefs.get("selectedTemperatureUnit", "°C");
    }

    private void updateUI() {
        selecaoCores.setSelectedItem(selectedColor);
        jComboBox1.setSelectedItem(selectedWindUnit);
        jComboBox2.setSelectedItem(selectedLanguage);
        jComboBox3.setSelectedItem(selectedTemperatureUnit);
    }

    private void savePreferences() {
        Preferences prefs = Preferences.userNodeForPackage(ConfigAparencia.class);
        prefs.put("selectedColor", selectedColor);
        prefs.put("selectedWindUnit", selectedWindUnit);
        prefs.put("selectedLanguage", selectedLanguage);
        prefs.put("selectedTemperatureUnit", selectedTemperatureUnit);
    }

    private void selecaoCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoCoresActionPerformed
        String selectedColor = selecaoCores.getSelectedItem().toString();
        if (selectedColor.equals("Padrão")) {
            Color color = new Color(214, 217, 223);
            painelPrincipal.setBackground(color);
            jLabel1.setForeground(Color.black);
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
            jLabel4.setForeground(Color.black);
        } else if (selectedColor.equals("Preto")) {
            jLabel1.setForeground(Color.white);
            jLabel2.setForeground(Color.white);
            jLabel3.setForeground(Color.white);
            jLabel4.setForeground(Color.white);
            painelPrincipal.setBackground(Color.black);
        } else if (selectedColor.equals("Branco")) {
            painelPrincipal.setBackground(Color.white);
            jLabel1.setForeground(Color.black);
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
            jLabel4.setForeground(Color.black);
        }
        savePreferences();
    }//GEN-LAST:event_selecaoCoresActionPerformed

    AppPrincipalVIEW appP = new AppPrincipalVIEW();

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String selectedTemperatureUnit = jComboBox3.getSelectedItem().toString();
            appP.mudarTemp(selectedTemperatureUnit);
        }
        savePreferences();
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String selectedWindUnit = jComboBox1.getSelectedItem().toString();
            appP.mudarVento(selectedWindUnit);
        }
        savePreferences();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        String selectedLanguage = jComboBox2.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigAparencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigAparencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigAparencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigAparencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigAparencia().setVisible(true);
            }
        });
    }

    private void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Assets/perereca_engracada.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel painelPrincipal;
    public javax.swing.JComboBox<String> selecaoCores;
    // End of variables declaration//GEN-END:variables
}
