/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.prefs.Preferences;
import javax.swing.JFrame;


/**
 *
 * @author mello
 */
public class FormularioLoginVIEW extends javax.swing.JFrame {

    /**
     * Creates new form FormulárioLoginVIEW
     */
    
    private static final String PREFS_NODE_NAME = "/com/example/loginform";
    private static final String REMEMBER_LOGIN_KEY = "rememberLogin";
    
    public FormularioLoginVIEW() {
        initComponents();
        this.setTitle("Weathervane");
        setIconImage();
        centreWindow(this);
        loadPreferences();
    }
    
    private void loadPreferences() {
        // Load preferences
        Preferences prefs = Preferences.userRoot().node(PREFS_NODE_NAME);
        lembrarLogin.setSelected(prefs.getBoolean(REMEMBER_LOGIN_KEY, false));

        // If "Remember Login" is selected, load the username and password
        if (lembrarLogin.isSelected()) {
            txtNomeUsuario.setText(prefs.get("username", ""));
            txtSenhaUsuario.setText(prefs.get("password", ""));
        }
    }

    private void savePreferences() {
        // Save preferences
        Preferences prefs = Preferences.userRoot().node(PREFS_NODE_NAME);
        prefs.putBoolean(REMEMBER_LOGIN_KEY, lembrarLogin.isSelected());

        // If "Remember Login" is selected, save the username and password
        if (lembrarLogin.isSelected()) {
            prefs.put("username", txtNomeUsuario.getText());
            prefs.put("password", new String(txtSenhaUsuario.getPassword()));
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnCriarConta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtSenhaUsuario = new javax.swing.JPasswordField();
        BtnLogin = new javax.swing.JButton();
        txtNomeUsuario = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        lembrarLogin = new javax.swing.JCheckBox();
        checkSenhaLogin = new javax.swing.JCheckBox();
        esqueci = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 520));
        jPanel1.setLayout(null);

        BtnCriarConta.setBackground(new java.awt.Color(255, 255, 255));
        BtnCriarConta.setForeground(new java.awt.Color(0, 0, 0));
        BtnCriarConta.setText("Criar Conta");
        BtnCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCriarContaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCriarConta);
        BtnCriarConta.setBounds(490, 430, 100, 23);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(null);

        txtSenhaUsuario.setBorder(null);
        txtSenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaUsuarioActionPerformed(evt);
            }
        });
        txtSenhaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaUsuarioKeyPressed(evt);
            }
        });
        jPanel2.add(txtSenhaUsuario);
        txtSenhaUsuario.setBounds(130, 190, 200, 20);

        BtnLogin.setBackground(new java.awt.Color(255, 255, 255));
        BtnLogin.setForeground(new java.awt.Color(0, 0, 0));
        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLogin);
        BtnLogin.setBounds(160, 370, 72, 23);

        txtNomeUsuario.setBorder(null);
        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });
        txtNomeUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeUsuarioKeyPressed(evt);
            }
        });
        jPanel2.add(txtNomeUsuario);
        txtNomeUsuario.setBounds(130, 140, 200, 20);

        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");
        jPanel2.add(Usuario);
        Usuario.setBounds(70, 140, 70, 20);

        Senha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Senha.setForeground(new java.awt.Color(255, 255, 255));
        Senha.setText("Senha");
        jPanel2.add(Senha);
        Senha.setBounds(70, 190, 70, 20);

        lembrarLogin.setForeground(new java.awt.Color(255, 255, 255));
        lembrarLogin.setText("Lembre de mim");
        lembrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lembrarLoginActionPerformed(evt);
            }
        });
        jPanel2.add(lembrarLogin);
        lembrarLogin.setBounds(210, 300, 120, 20);

        checkSenhaLogin.setForeground(new java.awt.Color(255, 255, 255));
        checkSenhaLogin.setText("Mostrar Senha");
        checkSenhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSenhaLoginActionPerformed(evt);
            }
        });
        jPanel2.add(checkSenhaLogin);
        checkSenhaLogin.setBounds(40, 290, 110, 40);

        esqueci.setForeground(new java.awt.Color(0, 153, 255));
        esqueci.setText("Esqueci a Senha");
        esqueci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esqueciMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                esqueciMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                esqueciMouseExited(evt);
            }
        });
        jPanel2.add(esqueci);
        esqueci.setBounds(240, 240, 100, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 10, 100, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bem-Vindo de Volta!");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 70, 150, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 20, 400, 480);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ainda não tem uma conta? Cadastre já!");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(490, 380, 320, 25);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/fundo-gradiente.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 520);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        Logar();
        savePreferences();

    }//GEN-LAST:event_BtnLoginActionPerformed

    private void txtSenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaUsuarioActionPerformed

    private void BtnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCriarContaActionPerformed

        //chamar tela de criar conta
        FormularioCriarContaVIEW objcriarcontaview = new FormularioCriarContaVIEW();
        objcriarcontaview.setVisible(true);

        dispose();

    }//GEN-LAST:event_BtnCriarContaActionPerformed

    private void checkSenhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSenhaLoginActionPerformed
        if (checkSenhaLogin.isSelected()) {
            txtSenhaUsuario.setEchoChar((char) 0);
        } else {
            txtSenhaUsuario.setEchoChar('*');
        }
    }//GEN-LAST:event_checkSenhaLoginActionPerformed

    private void txtSenhaUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Logar();
        }
    }//GEN-LAST:event_txtSenhaUsuarioKeyPressed

    private void txtNomeUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSenhaUsuario.requestFocus();
        }

    }//GEN-LAST:event_txtNomeUsuarioKeyPressed

    private void lembrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lembrarLoginActionPerformed

    }//GEN-LAST:event_lembrarLoginActionPerformed

    private void esqueciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esqueciMouseClicked
        EsqueceuSenha forgor = new EsqueceuSenha();
        forgor.setVisible(true);
        dispose();
    }//GEN-LAST:event_esqueciMouseClicked

    private void esqueciMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esqueciMouseEntered
        esqueci.setForeground(Color.gray);
    }//GEN-LAST:event_esqueciMouseEntered

    private void esqueciMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esqueciMouseExited
        Color color = new Color(0,153,255);
        esqueci.setForeground(color);
    }//GEN-LAST:event_esqueciMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioLoginVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCriarConta;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Usuario;
    private javax.swing.JCheckBox checkSenhaLogin;
    private javax.swing.JLabel esqueci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JCheckBox lembrarLogin;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JPasswordField txtSenhaUsuario;
    // End of variables declaration//GEN-END:variables

    private void Logar() {
        try {
            String nome_usuario, senha_usuario;

            nome_usuario = txtNomeUsuario.getText();
            senha_usuario = txtSenhaUsuario.getText();

            UsuarioDTO objusuariodto = new UsuarioDTO();
            objusuariodto.setNome_usuario(nome_usuario);
            objusuariodto.setSenha_usuario(senha_usuario);

            UsuarioDAO objusuariodao = new UsuarioDAO();
            ResultSet rsusuariodao = objusuariodao.autenticacaoUsuario(objusuariodto);

            if (rsusuariodao.next()) {
                //chamar tela principal
                AppPrincipalVIEW objappprincipalview = new AppPrincipalVIEW();
                objappprincipalview.setVisible(true);

                dispose();
            } else {
                //mostrar mensagem que tá errado
                JOptionPane.showMessageDialog(null, "Usuario ou Senha Inválida");
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "FormularioLoginVIEW: " + error);
        }
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Assets/perereca_engracada.png")));
    }
    
    private void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    
    private static void closeFrame(JFrame frame) {
        WindowEvent windowClosing = new WindowEvent(frame, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClosing);
    }
}
